#!/usr/bin/perl

use strict;

# this perl script simply substitutes a set of street suffixes (and their
# mapping into our internal address mapping code) into ragel and C source 
# code. the main point of this is to allow us to define this information in
# only one single place.

my %suffix_mapping = (
    "av" => "Address::AVENUE",
    "ave" => "Address::AVENUE",
    "aven" => "Address::AVENUE",
    "avenu" => "Address::AVENUE",
    "avenue" => "Address::AVENUE",
    "avn" => "Address::AVENUE",
    "avnue" => "Address::AVENUE",
    "blvd" => "Address::BOULEVARD",
    "boul" => "Address::BOULEVARD",
    "boulevard" => "Address::BOULEVARD",
    "boulv" => "Address::BOULEVARD",
    "crecent" => "Address::CRESCENT",
    "cres" => "Address::CRESCENT",
    "crescent" => "Address::CRESCENT",
    "cresent" => "Address::CRESCENT",
    "dr" => "Address::DRIVE",
    "driv" => "Address::DRIVE",
    "drive" => "Address::DRIVE",
    "drives" => "Address::DRIVE",
    "highway" => "Address::HIGHWAY",
    "highwy" => "Address::HIGHWAY",
    "hiway" => "Address::HIGHWAY",
    "hiwy" => "Address::HIGHWAY",
    "hwy" => "Address::HIGHWAY",
    "la" => "Address::LANE",
    "lane" => "Address::LANE",
    "lanes" => "Address::LANE",
    "ln" => "Address::LANE",
    "rd" => "Address::ROAD",
    "ro" => "Address::ROW",
    "road" => "Address::ROAD",
    "rotary" => "Address::ROTARY",
    "row" => "Address::ROW",
    "rtry" => "Address::ROTARY",
    "st" => "Address::STREET",
    "street" => "Address::STREET",
    "streets" => "Address::STREET",
    "strt" => "Address::STREET",
    "ter" => "Address::TERRACE",
    "terr" => "Address::TERRACE",
    "terrace" => "Address::TERRACE",
);

my @all_suffixes_sorted = sort(keys %suffix_mapping);

my @all_values_sorted;
foreach my $suffix (@all_suffixes_sorted) {
    push @all_values_sorted, $suffix_mapping{$suffix};
}

my $all_suffixes_rl = join("|", map { "\"$_\"" } @all_suffixes_sorted);
my $all_suffixes_c = join(", ", map { "\"$_\"" } @all_suffixes_sorted);
my $all_values_c = join(", ", @all_values_sorted);

print "/* This file has been automatically generated by suffix-subst.pl. */\n";

while (<STDIN>) {    
    s/\@SUFFIX_NAMES_C\@/$all_suffixes_c/;
    s/\@SUFFIX_VALUES_C\@/$all_values_c/;
    s/\@SUFFIX_NAMES_RL\@/$all_suffixes_rl/;
    print $_;
}
